data:
  train_path: './dataset/'
  img_size: 256

network:
  voxel_output: 64
  base_channels: 64
  dim_mults: [1,2,4,8,16]
  dropout: 0.1
  img_backbone: 'Resnet50'
  img_backbone_dim: 1024
  with_attention: False

results:
  results_folder: './results'
  save_top_k: 5
  save_last: True

train:
  devices: 2
  batch_size: 1
  lr: 1.0e-3
  optimizier: "adam"
  scheduler: "CosineAnnealingLR"
  training_epoch: 1000
  ema_rate: 0.99
  gradient_clip_val: 1.0
  noise_schedule: "linear"
  debug: False

wandb:
  wandb_key: "c2e2576d7570d6b9d296838ab73e0383f15158fc"

verbose: False
seed: 566